#### Q8: List Vs Tuple

In [8]:
list = ['a', 2, 3.4]
print('List: ',list)

tuple = ('a', 2, 3.4)
print('Tuple: ',tuple)

List:  ['a', 2, 3.4]
Tuple:  ('a', 2, 3.4)


### Scope of Variable:
#### Q9 : Local Variable and Global Variable

In [13]:
global_variable = 24
def var_func():
    local_variable = 12
    print(global_variable)
    print(local_variable)

var_func()

24
12


#### Q12: Array Vs List:

In [18]:
#list:
list = [1, 'hi', 4.5]
list

[1, 'hi', 4.5]

In [3]:
#Array:
import array as arr   #from array import *

a = arr.array('i',[1,2,3,4,5,6])
print(a)

##Access:
print(a[2])  #a[index]
print(a[-2])

len(a)

array('i', [1, 2, 3, 4, 5, 6])
3
5


6

#### Q13: Add values to python array

In [4]:
a.append(7) #at last single value
print(a)
a.extend([8,9,10]) #at last multiple values
print(a)
a.insert(1, 120) #(index, value)
print(a)

array('i', [1, 2, 3, 4, 5, 6, 7])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array('i', [1, 120, 2, 3, 4, 5, 6, 7, 8, 9, 10])


#### Q14: Remove values from python array

In [5]:
a.pop(1)#pop(index)
a.remove(7)#remove(value)
a

array('i', [1, 2, 3, 4, 5, 6, 8, 9, 10])

#### Q16: List and Dict Comprehension

List Comprehension:

In [7]:
num = [1,2,3,4,5,6,7,8,9,10]
#my_num = []
#for n in num:
#    my_num.append(n)
#print(my_num)

my_num = [n for n in my_num]  #exact same result as for given above.
print(my_num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
#my_num = []
#for n in num:
#    my_num.append(n*n)
#print(my_num)

my_num = [n*n for n in my_num]  #exact same result as for given above.
print(my_num)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [10]:
#even_list = []
#for n in num:
#    if n%2==0:
#        even_list.append(n)
#print(even_list)

even_list = [n for n in num if n%2==0]
print(even_list)

[2, 4, 6, 8, 10]


In [12]:
#NESTED FOR LOOP:
#my_list =[]
#for letter in 'abcd':
#    for num in range(4):
#        my_list.append((letter,num))
#print(my_list)

my_list = [(letter, num) for letter in 'abcd' for num in range(4)]
print(my_list)

[('a', 0), ('a', 1), ('a', 2), ('a', 3), ('b', 0), ('b', 1), ('b', 2), ('b', 3), ('c', 0), ('c', 1), ('c', 2), ('c', 3), ('d', 0), ('d', 1), ('d', 2), ('d', 3)]


Dict Comprehension

In [22]:
ids = [1,2,3,4,5,6]
names = ['a','b','c','d','e','f']
list(zip(ids, names))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e'), (6, 'f')]

In [24]:
my_dict = {id: name for id , name in zip(ids, names)}
print(my_dict)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f'}


#### Q17: Lambda Function:

In [20]:
func_name = lambda a,b: a + b
print(func_name(2,3))

5


#### Q18: Range Vs XRange

In [2]:
#Range => range(start, stop, step) 
x = range(6)
for i in x:
    print(i)

print(type(x))

0
1
2
3
4
5
<class 'range'>


In [24]:
y = range(5, 20, 5)
for j in y:
    print(j)

5
10
15


In [28]:
#XRange =>
a = xrange(6)
#NOTE: XRange is only till python 2

NameError: name 'xrange' is not defined

#### Q24: Single star args and Double star args

In [30]:
def person(name, *data):
    print(name)
    print(data)

person('Asad', 24, 'Mum', 9820)

Asad
(24, 'Mum', 9820)


In [31]:
def person(name, **data):
    print(name)
    print(data)

person('Asad', age=24, city='Mum', mob=9820)

Asad
{'age': 24, 'city': 'Mum', 'mob': 9820}


In [33]:
def person(name, **data):
    print(name)
    for i,j in data.items():
        print(i,j)
    
person('Asad', age=24, city='Mum', mob=9820)

Asad
age 24
city Mum
mob 9820


#### Q26: Len()

In [34]:
a = 'Hi, how are you'
len(a)

15

In [35]:
b = ['Asad', 12, 7.3]
len(b)

3

#### Q27: split(), sub(), subn()

In [31]:
a = 'Hi!! how are you'
a = a.split(' ')
a

['Hi!!', 'how', 'are', 'you']

In [40]:
import re
b = 'jhdwihdwidnidhvmnaxmuywuws'
re.sub('[hd]', 'HD', b)

'jHDHDwiHDHDwiHDniHDHDvmnaxmuywuws'

In [43]:
re.subn('[hd]', 'HD', b, 20)

('jHDHDwiHDHDwiHDniHDHDvmnaxmuywuws', 7)

#### Q33: break, continue, pass

In [2]:
x = int(input('Enter Num: '))
i =1
while i <= x:
    print('Success')
    i += 1

print('Bye')

Enter Num: 8
Success
Success
Success
Success
Success
Success
Success
Success
Bye


In [7]:
#break:
num = 5
x = int(input('Enter Number: '))
i =1
while i <= x:
    if i > num:
        print('out of range, only ', num, ' times can be printed')
        break
        
    print('Success')
    i += 1

print('Bye')

Enter Number: 2
Success
Success
Bye


In [9]:
#continue:
for i in range(1, 20):
    if i%3==0 or i%5==0: #number divisible by 3 and 5 will not be displayed
        continue
    
    print(i)
print('Bye')

1
2
4
7
8
11
13
14
16
17
19
Bye


#### Q36: Slicing

In [10]:
a = [1,2,3,4,5,6,7,8]
a[0:3]

[1, 2, 3]

#### Q38: Number - String

In [14]:
a = 655
print(type(a))
b = str(a)
print(type(b))

<class 'int'>
<class 'str'>


# Object Oriented Programming:

#### Q43: Self

In [20]:
class Employee:
    
    def empdetails(self):
        return f"for Name {self.name}, Salary is {self.sal}, Role is {self.role}"
    
harry = Employee()
nigin = Employee()

harry.name = 'Harry'
harry.sal = 2
harry.role = 'intern'

nigin.name = 'Nigin'
nigin.sal = 10
nigin.role = 'HR'

print (harry.empdetails())
print (nigin.empdetails())

for Name Harry, Salary is 2, Role is intern
for Name Nigin, Salary is 10, Role is HR


#### Q42: init => SPECIAL METHOD

In [24]:
class Employee:
    def __init__(self, aname, asal, arole):
        self.name = aname    #name is instance name and aname is argument
        self.sal = asal
        self.role = arole

nigin = Employee('Nigin', 10, 'HR')

print(nigin.sal)
print(nigin.name)

10
Nigin


#### Q48: Inheritance

In [1]:
class A:
    def func1(self):
        print('This is class A')

class B:
    def func2(self):
        print('This is class B')

obj_a = A()
obj_b = B()

obj_a.func1()
#obj_b.func1()
obj_b.func2()

This is class A
This is class B


In [2]:
class Parent:
    def func1(self):
        print('This is class A')

class Child(Parent):
    def func2(self):
        print('This is class B')

obj = Child()  #creating object of Child class.

obj.func1()
obj.func2()

This is class A
This is class B


In [3]:
# __init__():

class Parent:
    def __init__(self, fname, fage):
        self.name = fname
        self.age = fage
        
    def view(self):
        print(self.name, self.age)

class Child(Parent):
    def __init__(self, fname, fage):
        Parent.__init__(self, fname, fage)
        self.lastname = 'Qadri'
    
    def view(self):
        print(self.lastname, self.name, self.age)

obj = Child('Asad', 18)  #creating object of Child class.

obj.view()

Qadri Asad 18


In [4]:
# Single Inheritance:

class Parent:
    def function1(self):
        print('this is Parent class')

class Child(Parent):
    def function2(self):
        print('this is Child class')

obj = Child()

obj.function1()  #obj of child class inherits function of parent class
obj.function2()

this is Parent class
this is Child class


In [5]:
# Multiple Inheritance:

class Parent1:
    def function1(self):
        print('this is Parent1 class')

class Parent2:
    def function2(self):
        print('this is Parent2 class')

class Child(Parent1, Parent2):
    def function3(self):
        print('this is Child class')

obj = Child()

obj.function1()
obj.function2()

this is Parent1 class
this is Parent2 class


In [6]:
# Multilevel Inheritance:

class Parent1:
    def function1(self):
        print('this is Parent1 class')

class Parent2(Parent1):
    def function2(self):
        print('this is Parent2 class')

class Child(Parent2):
    def function3(self):
        print('this is Child class')

obj = Child()

obj.function1()
obj.function2()

this is Parent1 class
this is Parent2 class


In [7]:
# Hierarchical Inheritance:

class Parent1:
    def function1(self):
        print('this is Parent1 class')

class Parent2(Parent1):
    def function2(self):
        print('this is Parent2 class')

class Child(Parent1):
    def function3(self):
        print('this is Child class')

obj1 = Parent2()
obj2 = Child()

print('Parent class object =>')
obj1.function1()
obj1.function2()

print('Child class object =>')
obj2.function1()
obj2.function3()

Parent class object =>
this is Parent1 class
this is Parent2 class
Child class object =>
this is Parent1 class
this is Child class


In [8]:
# Hybrid Inheriance:

class Parent1:
    def function1(self):
        print('this is Parent1 class')

class Parent2():
    def function2(self):
        print('this is Parent2 class')

class Parent3(Parent1):
    def function3(self):
        print('this is Parent3 class')

class Child(Parent1, Parent2):
    def function3(self):
        print('this is Child class')

obj1 = Parent3()
obj2 = Child()

print('Parent3 class object =>')
obj1.function1()
obj1.function3()

print('Child class object =>')
obj2.function1()
obj2.function2()

Parent3 class object =>
this is Parent1 class
this is Parent3 class
Child class object =>
this is Parent1 class
this is Parent2 class


In [9]:
# Self
class Parent:
    def function1(self):
        print('this is function1 of Parent class')

class Child(Parent):
    def function2(self):
        super().function1()   #super class will call function1 whenever function2 is called.
        print('this is function2 of Child class')

obj = Child()
obj.function2()

this is function1 of Parent class
this is function2 of Child class


In [10]:
# Method Overriding:
class Parent:
    def function1(self):
        print('this is function1 of Parent class')

class Child(Parent):
    def function1(self):   #method overriding bcoz same function name in both the classes.
        print('this is function2 of Child class')

obj = Child()
obj.function1()

this is function2 of Child class


In [1]:
class Employee:

    raise_amt = 1.04

    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay

    def fullname(self):
        return '{} {}'.format(self.first, self.last)

    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amt)


dev_1 = Employee('Corey', 'Schafer', 50000)
dev_2 = Employee('Test', 'Employee', 60000)

print(dev_1.email)
print(dev_2.email)   

Corey.Schafer@email.com
Test.Employee@email.com


In [2]:
class Employee:

    raise_amt = 1.04

    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay

    def fullname(self):
        return '{} {}'.format(self.first, self.last)

    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amt)


class Developer(Employee):
    raise_amt = 1.10

    def __init__(self, first, last, pay, prog_lang):
        super().__init__(first, last, pay)
        self.prog_lang = prog_lang


class Manager(Employee):

    def __init__(self, first, last, pay, employees=None):
        super().__init__(first, last, pay)
        if employees is None:
            self.employees = []
        else:
            self.employees = employees

    def add_emp(self, emp):
        if emp not in self.employees:
            self.employees.append(emp)

    def remove_emp(self, emp):
        if emp in self.employees:
            self.employees.remove(emp)

    def print_emps(self):
        for emp in self.employees:
            print('-->', emp.fullname())


dev_1 = Developer('Corey', 'Schafer', 50000, 'Python')
dev_2 = Developer('Test', 'Employee', 60000, 'Java')

mgr_1 = Manager('Sue', 'Smith', 90000, [dev_1])

print(mgr_1.email)

mgr_1.add_emp(dev_2)
mgr_1.remove_emp(dev_2)

mgr_1.print_emps()

Sue.Smith@email.com
--> Corey Schafer


#### Q49: Polymorphism

In [1]:
class French:
    def say_hello(self):
        print('Bonjour')

class English:
    def say_hello(self):
        print('Hi')

def intro(lang):
    lang.say_hello()

john = French()
asad = English()

intro(asad)
intro(john)

Hi
Bonjour


In [2]:
#Abstract Polymorphism:
class Language:
    def say_hello(self):
        raise NotImplementedError('Please use say_hello method in child class')
    
    
class French(Language):
    pass
#     def say_hello(self):
#         print('Bonjour')

class English(Language):
    def say_hello(self):
        print('Hi')

def intro(lang):
    lang.say_hello()

john = French()
asad = English()

intro(asad)
intro(john)

#NOTE: ERROR INTENTIIONALLY KEPT FOR THE SAKE OF UNDERSTANDING

Hi


NotImplementedError: Please use say_hello method in child class

In [3]:
# Duck Typing - Polymorphism:
class PyCharm:
    def execute(self):
        print('Compiling')
        print('Running...')

class MyIDE:
    def execute(self):
        print('Convention Check')
        print('Compiling')
        print('Running...')

class Laptop:
    def code(self, ide):
        ide.execute()

ide = MyIDE() #ide = PyCharm()

lap1 = Laptop()
lap1.code(ide)

Convention Check
Compiling
Running...


#### Q50: Encapsulation

In [5]:
class TechAsad():
    def __init__(self):
        self.tech = 'Python'
        self.__course = 'Python ML'    #Abstracyed / Encapsulated variable
    
    def CourseName(self):
        return self.tech +' : '+self.__course

obj = TechAsad()

print(obj.tech)
print(obj._TechAsad__course)
print(obj.CourseName())

Python
Python ML
Python : Python ML


#### Q51: Filter(), Map(), Reduce()

In [1]:
func_list = [1,2,3,4,5,6,7,8,9,10]

In [2]:
# Filter Function:
#Filtering consists of applying a predicate or Boolean-valued function to an iterable to generate a new iterable. Items in the
#new iterable are produced by filtering out any items in the original iterable.

#filter(function, iterable)
#function - function that tests if elements of an iterable return true or false.
#iterable - iterable which is to be filtered, could be sets, lists, tuples, or containers of any iterators


#Using normal function:
# def is_even(n):
#     return n%2==0

# evens = list(filter(is_even, func_list))
# print(evens)

#Using lambda function:
evens_lambda = list(filter(lambda n:n%2==0, func_list))
print(evens_lambda)

[2, 4, 6, 8, 10]


In [3]:
# Map Function:     => to change each n every value together
#Mapping consists of applying a transformation function to an iterable to produce a new iterable. Items in the new iterable
#are produced by calling the transformation function on each item in the original iterable.

#map(fun, iter)
#=>fun : It is a function to which map passes each element of given iterable.
#=>iter : It is a iterable which is to be mapped. 

double_val = list(map(lambda n:n*2, evens_lambda))
print(double_val)

[4, 8, 12, 16, 20]


In [4]:
# Reduce Function:
#Reducing consists of applying a reduction function to an iterable to produce a single cumulative value.

#reduce(fun,seq)

from functools import reduce
sum_val = reduce(lambda a, b: a+b, double_val)
print(sum_val)

60


# Pandas

In [1]:
import pandas as pd

In [2]:
file = pd.read_csv('patient.csv')
file

Height      Weight   BP  Diabetic Gender
0  73.847017  241.893563   98       150      M
1  68.781904  162.310473   99       145      F
2  74.110105  212.740856  110       298     SM
3  71.730978  220.042470   89       199      F
4  69.881796  206.349801   97       177      F

In [3]:
# Rename Column:
file = file.rename(columns = {file.columns[2]:'BPressure'}, inplace = False)
file.head()

Height      Weight  BPressure  Diabetic Gender
0  73.847017  241.893563         98       150      M
1  68.781904  162.310473         99       145      F
2  74.110105  212.740856        110       298     SM
3  71.730978  220.042470         89       199      F
4  69.881796  206.349801         97       177      F

In [4]:
# Unique Values:
unique_gen = file.Gender.unique()
print(len(unique_gen))
unique_gen

3


array(['M', 'F', 'SM'], dtype=object)

In [5]:
#Select specific columns:   #can also be done using iloc
new_file = file[['Height','Weight','Gender']]
new_file

Height      Weight Gender
0  73.847017  241.893563      M
1  68.781904  162.310473      F
2  74.110105  212.740856     SM
3  71.730978  220.042470      F
4  69.881796  206.349801      F

In [6]:
#Drop specific columns:
dropped_data = file.drop('Gender',1)  #1 for column
#dropped_data = file.drop('Gender',0) #0 for row
print(len(dropped_data))
dropped_data

5


Height      Weight  BPressure  Diabetic
0  73.847017  241.893563         98       150
1  68.781904  162.310473         99       145
2  74.110105  212.740856        110       298
3  71.730978  220.042470         89       199
4  69.881796  206.349801         97       177

# Numpy

In [7]:
import numpy as np

In [8]:
#Create numpy array from scratch:
array1 = np.zeros(5)
array1

array([0., 0., 0., 0., 0.])

In [9]:
array2 = np.array([2,3,4,5,6], dtype = np.float32)
array2

array([2., 3., 4., 5., 6.], dtype=float32)

In [10]:
#Create a multidimensional array: => create numpy matrix
array1.shape = (5,1)
array1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
array1.shape = (1,5)
array1

array([[0., 0., 0., 0., 0.]])

In [12]:
array3 = np.zeros((2,3))
array3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#Create array within range:
array4 = np.linspace(2,8,4)
array4

array([2., 4., 6., 8.])

In [14]:
#Add, remove and sort elements within np array:
test_array = np.array([1,2,3,4])
print(test_array)

[1 2 3 4]


In [15]:
#add:
test1 = np.append(test_array,[5,6])
test1

array([1, 2, 3, 4, 5, 6])

In [16]:
#delete:
test2 = np.delete(test_array,0)
test2

array([2, 3, 4])

In [17]:
#sort:
unsorted_array = np.array([1,3,2,4,7,5,20,6])
sorted_array = np.sort(unsorted_array)
sorted_array

array([ 1,  2,  3,  4,  5,  6,  7, 20])

In [18]:
#Indexing and Slicing:
array5 = np.array([1,2,3,4])
print(array5[0])
print(array5[1])

print(array5[0:2])
print(array5[1:])
print(array5[-2:])

1
2
[1 2]
[2 3 4]
[3 4]
